spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AengusMa/config-repo
          username: mwljndx@163.com
          password: xxxx
  rabbitmq:
    host: 111.231.228.108
eureka:
  client:
    service-url:
      defaultZone: http://111.231.228.108:8761/eureka/
server:
  port: 6062
management:
  endpoints:
    web:
      exposure:
        include: "*"