spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AengusMa/config-repo
          username: mwljndx@163.com
          password: xxxx
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
server:
  port: 9001