spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.99.100:3306/springcloud_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/