eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
    register-with-eureka: false
#开发环境关闭（自我保护模式）
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8761